#!/usr/bin/env ruby

require 'erb'
version = ARGV.fetch(0)
stemcell_version = ARGV.fetch(1)
release_file_name = ARGV.fetch(2)

major_and_minor_version = version.split('.').slice(0,2).join('_')

metadata_template = File.join(__dir__, 'metadata', 'example-product.yml.erb')
puts ERB.new(File.read(metadata_template)).result
