#!/usr/bin/env ruby
require 'erb'

version = ARGV.fetch(0)
major_and_minor_version = version.split('.').slice(0, 2).join('_')
# If we have 99+ minor versions, this will fail as the filename generated below
#  must be in the format YYYMMDDHHMM_*.js
minor_version = version.split('.')[1] || '00'
minor_version.prepend('0') if minor_version.length == 1

Dir.glob(File.join(__dir__, 'migration_templates', '*.erb')).each do |template_file_path|
  filled_template = ERB.new(File.read(template_file_path)).result

  # Include the current major/minor version number in the migration name to ensure that it will not be
  # named the same or have the same timestamp as in the previous minor version of the example tile.
  output_filename = '2017050602' + minor_version + '_' + File.basename(template_file_path, '.js.erb') + major_and_minor_version + '.js'
  output_full_path = File.join(__dir__, 'migrations', 'v1', output_filename)

  File.write(output_full_path, filled_template)
end
