#!/bin/bash
set -e

RUN_DIR=/var/vcap/sys/run/anemic_service_broker
PIDFILE=${RUN_DIR}/pidfile

case $1 in
  start)
    mkdir -p $RUN_DIR

    echo '1' > $PIDFILE
    ;;

  stop)
    rm -f $PIDFILE
    ;;

  *)
    echo "Usage: ctl {start|stop}"
  ;;

esac
