#!/usr/bin/env ruby

require 'erb'
require 'active_support/inflector'

version = ARGV.fetch(0)
stemcell_version = ARGV.fetch(1)
release_file_name = ARGV.fetch(2)
product_name = ARGV.fetch(3)
suffix = ARGV.fetch(4) == "" ? nil : ARGV.fetch(4)
stemcell_os = ARGV.fetch(5) == "" ? "ubuntu-trusty" : ARGV.fetch(5)
bpm_version = ARGV.fetch(6)
os_conf_version = ARGV.fetch(7)

match_data = /(?<major_version>\d+)\.(?<minor_version>\d+)[.\-]/.match(version)
minor_version = match_data[:minor_version]
major_version = match_data[:major_version]
major_and_minor_version = "#{major_version}_#{minor_version}"

metadata_template = File.join(__dir__, product_name, 'metadata', "#{product_name}.yml.erb")
puts ERB.new(File.read(metadata_template), trim_mode:'-').result
