#!/usr/bin/env bash
set -eu

# install dependencies
apt-get update
apt-get install -y zip
gem install bosh_cli


#find the release with the largest number
release_file=$(ruby "${REPO_DIR}/ci/scripts/latest_release.rb" "${REPO_DIR}/example-release/releases/example-release")

cd $REPO_DIR/example-release

echo "creating release ${release_file}"
bosh create release $release_file

echo "moving releases"
mv releases/example-release/*.tgz ../example-product/releases/

echo "creating .pivotal file"
cd ../example-product

zip -r generated-example-product.pivotal metadata releases/
