#!/usr/bin/env bash
set -eux

root_dir=$(pwd)
version_num="$(cat version_1_5/number)"
product_dir="${root_dir}/ops-manager-example/example-product"
release_dir="${root_dir}/ops-manager-example/example-release"

# install dependencies
if [[ -x "$(command -v apt-get)" ]]; then
  apt-get update
  apt-get install -y zip
fi

cd "${release_dir}"

bundle # installs bosh_cli

echo "removing any previous release tarballs"
rm -f releases/example-release/*.tgz

release_yml=$(ls releases/example-release/example-release-*.yml| sort| tail -1)
echo "creating release from ${release_yml}"
bundle exec bosh create release "${release_yml}" --with-tarball

release_tgz=$(ls releases/example-release/example-release-*.tgz| sort| tail -1)
if [[ ! -f ${release_tgz} ]]; then
  echo "No release created from ${release_yml}"
  exit 1
fi

echo "moving release ${release_tgz} to "
mv "${release_tgz}" "${product_dir}/releases/"

cd "${product_dir}"
echo "creating .pivotal file"

zip -r example-product-$version_num.pivotal content_migrations metadata releases
