#!/usr/bin/env bash

set -ue

OUTPUT_DIR=${1}

cd "$(dirname ${0})"
if [[ -n ${DEV_RELEASE:-} ]]; then
  RELEASES_DIR="dev_releases"
else
  RELEASES_DIR="releases"
fi

echo "removing any previous release tarballs"
rm -f ${RELEASES_DIR}/example-release/*.tgz

release_yml=$(ls ${RELEASES_DIR}/example-release/example-release-*.yml | sort -t '-' -k 4 -g | tail -1)
echo "creating release from ${release_yml}"
bosh create-release "${release_yml}" --force --tarball=${RELEASES_DIR}/example-release/example-release-$$.tgz

release_tgz=$(ls ${RELEASES_DIR}/example-release/example-release-*.tgz | sort -t '-' -k 4 -g | tail -1)
if [[ ! -f ${release_tgz} ]]; then
  echo "No release created from ${release_yml}"
  exit 1
fi

echo "moving release ${release_tgz} to ${OUTPUT_DIR}"
mv "${release_tgz}" "${OUTPUT_DIR}"
