#!/usr/bin/env ruby

require 'rubygems'
require 'active_support'

def example_product_version
  ARGV[0] || fail("Must provide the OM version. For example, on the releases/1.9 branch run '#{$0} 1.9'")
end

def next_release_build
  release_file_names = Dir.glob(
    File.expand_path("releases/example-release/example-release-#{example_product_version}.release*.yml", __dir__)
  )
  build_versions = release_file_names.map {|file_name| file_name.match(/\.release(\d+).yml\z/)[1].to_i }
  most_recent_build_version = build_versions.max
  "#{example_product_version}.release#{most_recent_build_version+1}"
end

puts "Cutting final release #{next_release_build.inspect}"
exec("cd #{__dir__}; bosh create release --final --version #{next_release_build} --force")
