#!/usr/bin/env ruby

require 'rubygems'
require 'yaml'

def example_product_version
  ARGV[0] || fail("Must provide the OM version. For example, on the releases/1.9 branch run '#{$0} 1.9'")
end

def next_release_build
  release_file_names = Dir.glob(
    File.expand_path("releases/example-release/example-release-*.release*.yml", __dir__)
  )
  build_versions = release_file_names.map {|file_name| file_name.match(/\.release(\d+).yml\z/)[1].to_i }
  most_recent_build_version = build_versions.max
  "#{example_product_version}.release#{most_recent_build_version+1}"
end

def main
  # These creds can be pulled from Concourse CredHub via:
  # export AWS_ACCESS_KEY_ID=$(credhub get -n /concourse/main/aws-assume-concourse-packer -k username) AWS_SECRET_ACCESS_KEY=$(credhub get -n /concourse/main/aws-assume-concourse-packer -k password) AWS_ROLE_ARN=$(credhub get -n /concourse/main/aws-assume-concourse-packer -k role_arn)
  aws_access_key_id = ENV.fetch('AWS_ACCESS_KEY_ID')
  aws_secret_access_key = ENV.fetch('AWS_SECRET_ACCESS_KEY')
  aws_role_arn = ENV.fetch('AWS_ROLE_ARN')
  private_yml_data = {
    blobstore: {
      provider: 's3',
      options: {
        access_key_id: aws_access_key_id,
        secret_access_key: aws_secret_access_key,
        assume_role_arn: aws_role_arn
      }
    }
  }
  private_yml_path = File.expand_path('config/private.yml', __dir__)
  begin
    File.write(private_yml_path, YAML.dump(private_yml_data))
    puts "Cutting final release #{next_release_build.inspect}"
    exec("cd #{__dir__}; bosh create-release --final --version #{next_release_build} --force")
  ensure
    File.delete(private_yml_path) if File.exist?(private_yml_path)
    end
end

main

